modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/CGessinger/Creatures-And-Beasts-Minecraft-Mod/issues"
[[mods]]
modId="cnb"
version="${file.jarVersion}"
displayName="Creatures and Beasts"
updateJSONURL="http://myurl.me/"
displayURL="https://github.com/CGessinger/Creatures-And-Beasts-Minecraft-Mod"
logoFile="logo.png"
credits="Thanks for this minecraft mod goes to Joosh and everyone who contributed to the project"
authors="CGessinger, Joosh, Azure Doom"
description='''
This is a simple minecraft mod which adds tons of new creatures. It is designed to make minecraft feel more alive and enhance the survival experience!
'''
[[dependencies.cnb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.cnb]]
    modId="geckolib"
    mandatory=true
    versionRange="[2.1.2,)"
    ordering="NONE"
    side="BOTH"
