modLoader="javafml"
loaderVersion="[41,)"
license="LGPLv3"
issueTrackerURL="https://github.com/CreaturesAndBeasts/Creatures_And_Beasts-Forge/issues"
[[mods]]
modId="cnb"
version="${file.jarVersion}"
displayName="Creatures and Beasts"
# updateJSONURL="http://myurl.me/"
displayURL="https://github.com/CreaturesAndBeasts/Creatures_And_Beasts-Forge"
logoFile="logo.png"
credits="Credits to AzureDoom and Christian for contributions to the code"
authors="Joosh, CGessinger, and HellionGames"
description='''
Creatures and Beasts is a vanilla-style creature mod which fills each biome with new mobs, from the plains of the overworld to the void of the end!
'''
[[dependencies.cnb]]
    modId = "forge"
    mandatory = true
    versionRange = "[41.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cnb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cnb]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.12,)"
    ordering="BEFORE"
    side="BOTH"
